steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/sagar-yt-skeleton/video-processing-repo/video-processing-service",
        ".",
      ]
